# version: "3.8"
# services:
#   web:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       - DATABASE_URL=postgresql://user:password@db:5432/mydb
#     depends_on:
#       - db
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydb
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
