export enum Ingredients {
  egg = "Egg base products",
  milk = "Milk base products",
  fat_oil = "Fat and Oil",
  fruits = "Fruits",
  grains = "Grains base products",
  nuts = "Nuts base products",
  baking = "Baking products",
  herbs = "Herbs",
  spices = "Spices",
  meats = "Meats",
  processes = "Processes products",
  fish = "Fish",
  pasta = "Pasta",
  noodle = "Noodle",
  rice = "Rice",
  pulses = "Pulses",
  vegetable = "Vegetables",
  other = "Other",
}
